- k8s-helm-charts/cns-team-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl
This is required as the cloudwatch metrics are filtering on 'error' not 'Error'.
> :wrench: Change Error to error

- k8s-helm-charts/cns-team-monitoring/Chart.yaml
Even though a redirect is in place from GitHub this change adds clarity for future users: 
`https://github.com/ministryofjustice/staff-infrastructure-monitoring-cluster`
-> 
`https://github.com/ministryofjustice/nvvs-devops-monitor`
> ♻ Update repo source

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
- k8s-helm-charts/cns-team-monitoring/templates/slack-webhooks-secrets.yaml
- k8s-helm-charts/cns-team-monitoring/values.yaml
- scripts/deploy.sh
This PR updates AlertManager with a new slack webhook for DNS DHCP slack channel alerts as well as splitting out critical alerts sent to PagerDuty.
> :test_tube: Configure DNS DHCP Alerts

- k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml
Increase DHCP error threshold while Empty DUIDs error's are being received. revert PR once error's stop.
> Increase-DHCP-Error-Threshold

- modules/eks/iam.tf
This is required to allow for the <65 character limit, which we hit at the moment in `development` and `pre-production` environments.
> :recycle: Refactor NLB name

- .terraform.lock.hcl
- modules/eks/iam.tf
- modules/eks/outputs.tf
This PR update logic by which Cloudwatch roles are created using terraform, without this logic a deployment to `development` fails.
> :wrench: Update Cloudwatch Role logic

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
Certificate expiring warnings are not required to be sent to PagerDuty for out-of-hours action. This PR will remove the PagerDuty config and only send the alert to the 'mojo-staff-certificate-services' slack channel.
> :wrench: Remove PagerDuty Alerts for Certificate warnings

- modules/eks/main.tf
This change has already been committed to the production EKS cluster manually. This PR brings the `main` branch into line with the current configuration.
> :wrench: Upgrade EKS v1.23 -> v1.24

- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
This PR sets the dashboard to load data for the last hour rather than a specific time range and also adds a 1m refresh.
before: 
after:
> :stethoscope: NACS Dashboard Update Time Range

- k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
changed DHCP server error sum alert threshold to 150 temporarily to allow us time to investigate the errors we are getting 
- DHCP discover packet from unknown IP
- Missing DUIDs
with a view to create alerts based on specific metric rather then from a metric that capture ALL errors and alerting based on that metric
> Dhcp alert rules

- .github/workflows/deployment_reusable_workflow.yml
- modules/eks/iam.tf
The make file can only be used when the AWS profile is setup. Currently this is only setup on the developer laptops and not GitHub actions. Thus the make file cannot be used within GitHub actions.
> fix error from baselining

- .github/dependabot.yml
- Amended directory for dependabot container scan - this will allow us to see outdated versions of the pinned container in that folder.
> Amended directory for dependabot container scan

- scripts/deploy.sh
- scripts/generate-env-file.sh
Use .env during local dev deployments
> Nd 430 - fix missing env values during helm deployment

- scripts/deploy.sh
.env file is used by local developers but it is not used in GitHub actions as the variables / secrets are passed in differently. This conditional change makes providing a .env file optional to the deploy script.
> condition the use of .env

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
- k8s-helm-charts/cns-team-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl
- k8s-helm-charts/cns-team-monitoring/templates/smtp-relay-alert-rules.yaml
- Adds Custom metric for postfix exporter 'FailedToScrape'
- adds alerting rules if there is an error sum > 1 in 5 mins 
- Updated SMTP Production service alarm route to go to DEVOPS critical SLACK Channel
> Nd 485 smtp metric

- k8s-values/values.kube-prometheus-stack.yaml
- Removing the DHCP API target fro dev and preprod as it not required and alerting unnecessarily
> removing DHCP API target for dev and prep as per ND-452

- modules/eks/main.tf
EKS upgrade was done using the command line - this change is to just reflect that in the terraform code to allow future deployments.
> changed eks version in terraform after upgrading using command line

- k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml
- remove 80% used alarm
- agreed on Team day (3rd March) 
- 90% alarm is still in place
> remove the 80% used subnet alarm to reduce noise in channel

- modules/eks/rds.tf
> corrected engine version to match what is in production

- scripts/deploy.sh
Deployment of [PR 314](https://github.com/ministryofjustice/nvvs-devops-monitor/pull/314) failed due to the bug introduced in external-dns Chart version 1.16.0. 
https://github.com/ministryofjustice/nvvs-devops-monitor/actions/runs/14214768815/job/39828827208
As a fix, I am pinning the external-dns chart version to 1.15.2
> pinned version to external-dns helm

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
Updated `certificate-services` channel from  `'#mojo-staff-infrastructure-certificate-services-alerts'` to `'#mojo-staff-certificate-services-alerts'`
> updated slack channel for certificate-services
