ministryofjustice/nvvs-devops-monitor

- k8s-values/values.aws-efs-csi-driver.yaml
- k8s-values/values.kube-prometheus-stack.yaml
> :truck: allocate more resources to prometheus and efs pods

- k8s-helm-charts/cns-team-monitoring/templates/cloudwatch-metrics/_production-metrics-custom.tpl
> :recycle: update cloudwatch metric name

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-alert-rules.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
- k8s-values/values.kube-prometheus-stack.yaml
- scripts/deploy.sh
fix templates, rules and routes
> :bug: fix slack notifications

- k8s-helm-charts/cns-team-monitoring/templates/blackbox-exporter-deployment.yaml
- k8s-helm-charts/cns-team-monitoring/templates/cloudwatch-exporter-deployment.yaml
- k8s-helm-charts/cns-team-monitoring/templates/json-exporter-deployment.yaml
- k8s-values/values.aws-efs-csi-driver.yaml
- k8s-values/values.aws-load-balancer-controller.yaml
- k8s-values/values.external-dns.yaml
- k8s-values/values.grafana.yaml
- k8s-values/values.ingress-nginx.yaml
- k8s-values/values.kube-prometheus-stack.yaml
- k8s-values/values.thanos-stack.yaml
it creates a lot of noise / alerts
> :fire: remove resource allocations

- .github/dependabot.yml
Update dependabot to monitor terraform files.
> 🤖 Update Dependabot

- k8s-helm-charts/cns-team-monitoring/templates/alertmanager-primary-alertmanagerconfig.yaml
> :pencil2: Fix Receiver Name

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/story-template.yml
- .github/labeler.yml
- .github/workflows/label-pull-request.yml
Added issues templates and GitHub label actions.
> :truck: Update GitHub Actions

- k8s-helm-charts/cns-team-monitoring/templates/kea-dhcp-metrics-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/values.yaml
- scripts/deploy.sh
added env variables for the NACS dashboard which are now being pulled from the parameter store rather than hardcoded. 
I have also updated the KEA DHCP dashboard to use the same env variables.
> :recycle: Environmnet Variables for NACS Dashboard

- k8s-helm-charts/cns-team-monitoring/templates/default-grafana-dashboard.yaml
Time was set statically, not to the last 15 minutes, this PR updates this.
> :memo: Update Home Page

- .github/workflows/deployment.yml
upgrade to configure-aws-credentials@v1-node16 branch
> :arrow_up: Update aws-actions to remove node12 deprecation warnings.

- modules/eks/main.tf
This change has already been committed to the production EKS cluster manually. This PR brings the main branch into line with the current configuration.
> :wrench: Upgrade EKS Cluster v1.24 -> v1.25

- k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml
> added alerting for Unhealthy container count in DNS ECS cluster

- .github/workflows/dependency-review.yml
- .github/workflows/deployment.yml
- .github/workflows/format-code.yml
- acm.tf
- modules/vpc/main.tf
- versions.tf
Reverts ministryofjustice/nvvs-devops-monitor#209
> Revert "Combined pr"

- .github/workflows/deployment.yml
Reverts ministryofjustice/nvvs-devops-monitor#210
> Revert "⬆️ Bump hashicorp/setup-terraform from 2 to 3"

- k8s-values/values.kube-prometheus-stack.yaml
as per https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-51x-to-52x this PR updates the thanos config values accordingly.
> update thanos config values

- .github/workflows/deployment_reusable_workflow.yml
- main.tf
- modules/eks/efs.tf
- modules/eks/node_groups.tf
- modules/eks/outputs.tf
- modules/eks/rds.tf
- modules/eks/variables.tf
- versions.tf
Update Terraform code to work correctly with the ENV switch
> Make env switch work correctly

- Makefile
- main.tf
- modules/eks/node_groups.tf
- modules/vpc/main.tf
Fixes issues found when trying to deploy development from scratch ( see commit messages for more detail)
> Terraform fixes

- modules/eks/iam.tf
- modules/vpc/main.tf
* Refactor have discussion with team
* Updated cross account IAM roles to centralise management to production for now
> Manage iam roles from one account

- modules/eks/iam.tf
- modules/vpc/main.tf
Reverts ministryofjustice/nvvs-devops-monitor#237
> Revert "Manage iam roles from one account"

- .github/workflows/deployment_reusable_workflow.yml
(cherry picked from commit e6e9aa66d9e7da5643853d8ab739989c0350f8e0)
> fix error fom baselining

- modules/eks/rds.tf
This PR is to fix the error in RDS.
RDS is already 14.10 in the coonsole
> match RDS version

- .github/dependabot.yml
ND-87
Added Docker to Dependabot to increase visibility on version updates.
> Added Docker to dependabot reviews

- k8s-helm-charts/cns-team-monitoring/templates/blackbox-exporter-deployment.yaml
- k8s-helm-charts/cns-team-monitoring/templates/json-exporter-deployment.yaml
Pinned JSON exporter and backbox exporter versions
> Pinned image versions

- .github/labeler.yml
- .github/workflows/label-pull-request.yml
- amended structure for labeler upgrade
- upgrade labeler from V4 to V5
> Labeler upgrade

- acm.tf
Added validation method argument as part of upgrade to v5.0.1
> added validation method to acm module

- k8s-values/values.thanos-stack.yaml
- Assigned resources to Thanos POD to address CPU throttling warning from EKS
>  Assigned resources to Thanos compactor POD 

- .env.tmp
- Makefile
- k8s-helm-charts/cns-team-monitoring-non-production/values-development.yaml
- modules/eks/policies/aws_load_balancer_iam_policy.json
- outputs.tf
- scripts/deploy.sh
- Deploys EKS cluster in Development 
- Fixed target group role for the EKS deployment 
- added make target for Garfana password for development
> Nd 115 eks dev deployment

- Makefile
- scripts/setup-kubeconfig.sh
- added script to get kubeconfig as a make target
> Kubeconfig 

- modules/eks/main.tf
- Upgrading EKS cluster version to kubernetes 1.26
> upgrading EKS to 1.26

- scripts/deploy.sh
Updated Grafana to latest release of version 10
> update grafana v10.3.1 -> v10.4.1

- k8s-helm-charts/cns-team-monitoring/templates/kea-dhcp-lease-statistics-grafana-dashboard.yaml
- Added panel for subnet specific statistics in kea dashboard
> added panel for subnet specific stats in kea lease stats dashboard

- .github/workflows/helm-chart-dependency.yml
- scripts/deploy.sh
- Pinned Kube-Prometheous-Stack version
- Added github workflow to check the version periodically( this is set to every night temporarily for testing)- No depenabot for helm chart
> Nd 62 pin kube prometheous stack

- documentation/upgrading-kubernetes.md
ND-622 Steps and commands to upgrade kubernetes version.
> Kubernetes documentation

- k8s-helm-charts/cns-team-monitoring/templates/bind-dns-metrics-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/kea-dhcp-metrics-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
- scripts/deploy.sh
- Fixed issues with Grafana labels
- Major upgrade 10 --> 11
> Nd 481 upgrade grafana to version 11 

- README.md
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-alert-rules.yaml
- added OCSP error alert 
- altered thresholds for some NACS alerts to stop the alarms obscuring real issues.
- values agreed by Matti
> dded alert for OCSP errors and changed thresholds

- k8s-helm-charts/cns-team-monitoring/templates/certificate-services-monitor-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-status-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/kea-dhcp-lease-statistics-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/kea-dhcp-metrics-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-grafana-dashboard.yaml
- k8s-helm-charts/cns-team-monitoring/templates/smtp-relay-grafana-dashboard.yaml
Added `"provisioned"` tag to our project specific dashboards
> added provisioned tag to project dashboards

- k8s-helm-charts/cns-team-monitoring/templates/network-access-control-alert-rules.yaml
Reverts ministryofjustice/nvvs-devops-monitor#318
> Revert "format fix"
